#!/usr/bin/env ruby

require 'drb'
require 'drb/timeridconv'
require 'script/gt_server.lib/server.rb'

DRb.install_id_conv(DRb::TimerIdConv.new) # keep objects on server alive
DRb.start_service("druby://:7777", GTServerClass.new)
puts "[***** GT DRB server running *****]"
STDOUT.flush
DRb.thread.join
puts "[***** GT DRB server shut down *****]"
STDOUT.flush
