#!/usr/bin/env ruby

require 'drb'

if ARGV.size != 1 then
  raise "Usage: gt_server_test gff3_file"
end

gff3_file = ARGV[0]

DRb.start_service
GTServer = DRbObject.new(nil, 'druby://localhost:7777')

puts GTServer.test_call()

errormsg = GTServer.gff3_errors(gff3_file)
if errormsg then
  raise "Error: #{errormsg}"
end

config = GTServer.config(1)

seqids = GTServer.gff3_seqids(gff3_file)
puts "types in #{gff3_file}:"
types = GTServer.gff3_feature_types(gff3_file)
types.each do |type|
  puts type
end
seqids.each do |seq_id|
  range = GTServer.gff3_range(gff3_file, seq_id)
  png_stream = GTServer.image(gff3_file, seq_id, range, config, 800, false)
  puts "png_stream.size=" + png_stream.size.to_s
end

puts GTServer.test_call()
